layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name
  include:
    projects:
      - gotty-repl
      - sish-lb
      - Go-interpreter
      - Set
      - Queue
      - raspi-mgr


social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: vickey.kumar.507464
  hackerrank: kumarvk
  # instagram: your_username
  # keybase: your_username
  linkedin: vickey-kumar-b9248a23
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: vickey_kmr
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Golang
    web_url: https://github.com/topics/golang
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/go/go.png

  - name: C
    web_url: https://github.com/topics/c
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/c/c.png

  - name: C++
    web_url: https://github.com/topics/cpp
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/cpp/cpp.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: Computer Networks
    web_url: https://github.com/topics/computer-networks
    
  - name: REST API
    web_url: https://github.com/topics/rest-api

  - name: Web design

  - name: data-mining
    web_url: https://github.com/topics/data-mining


google_verify: -Bkw7pK7wtbIc03TqHlnSuqfdkLHkRkkp9SgzRRgPlQ


theme: jekyll-theme-tactile